# Generated by Django 5.1 on 2024-08-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
