# Generated by Django 5.1.1 on 2024-09-07 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customlogentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomLogEntry',
        ),
    ]
